DROP TABLE IF EXISTS BOOKINGTICKET;
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS ATTRACTION;
DROP TABLE IF EXISTS CUSTOMER;
