-- שליפת כל הנתונים מכל הטבלאות
SELECT * FROM CUSTOMER;
SELECT * FROM ATTRACTION;
SELECT * FROM PAYMENT;
SELECT * FROM BOOKING;
SELECT * FROM TICKET;
SELECT * FROM REVIEW;
SELECT * FROM BOOKINGTICKET;

-- ספירת כמות הרשומות בכל טבלה
SELECT 'CUSTOMER' AS table_name, COUNT(*) FROM CUSTOMER;
SELECT 'ATTRACTION' AS table_name, COUNT(*) FROM ATTRACTION;
SELECT 'PAYMENT' AS table_name, COUNT(*) FROM PAYMENT;
SELECT 'BOOKING' AS table_name, COUNT(*) FROM BOOKING;
SELECT 'TICKET' AS table_name, COUNT(*) FROM TICKET;
SELECT 'REVIEW' AS table_name, COUNT(*) FROM REVIEW;
SELECT 'BOOKINGTICKET' AS table_name, COUNT(*) FROM BOOKINGTICKET;
