SELECT * FROM CUSTOMER ORDER BY customer_id;
SELECT * FROM ATTRACTION ORDER BY attraction_id;
SELECT * FROM PAYMENT ORDER BY payment_id;
SELECT * FROM BOOKING ORDER BY booking_id;
SELECT * FROM TICKET ORDER BY ticket_id;
SELECT * FROM REVIEW ORDER BY review_id;
SELECT * FROM BOOKINGTICKET ORDER BY booking_id, ticket_id;
